AllCops:
  TargetRubyVersion: 3.0

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'it']

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Lint/AmbiguousBlockAssociation:
  Enabled: true

Style/Documentation:
  Enabled: false

  Style/FrozenStringLiteralComment:
    Enabled: false
